no really the end of day check in

diff --git a/.workbench/.bak/fnusedlib b/.workbench/.bak/fnusedlib
--- a/.workbench/.bak/fnusedlib
+++ b/.workbench/.bak/fnusedlib
@@ -1,18 +1,16 @@
 # 2025-12-01: copied from .prior-work-files/lib/fun/cleanlib
-# 
+# 2025-12-14: updated to manage zsh / bash diffs (further cleanup expected)
 debug ()
 {
     return
 }
 debug_off ()
 {
-    : no diagnostics, just return;
+    : no diagnostics, redefine debug to just return;
     : date: 2023-03-29;
     : date: 2024-11-05;
-    function debug () 
-    { 
-        return
-    }
+    : date: 2025-12-14: copyedits;
+    debug () { return }
 }
 debug_on ()
 {
@@ -22,7 +20,14 @@ debug_on ()
     : date: 2022-03-07;
     : date: 2023-01-30;
     : date: 2024-11-05;
-    eval "debug () { printf \"%-21s\\t%-21s\\t%-21s : %s\\n\" \${FUNCNAME[3]} \${FUNCNAME[2]} \${FUNCNAME[1]} \"\$*\" 1>&2; }"
+    : date: 2025-12-14: zsh / bash differences;
+    if [[ -n $ZSH_VERSION ]]; then
+        debug () { printf "%-21s\t%-21s\t%-21s : %s\n" ${funcstack[4]} ${funcstack[3]} ${funcstack[2]} "$*" 1>&2 }
+    elif [[ -n $BASH_VERSION ]]; then
+        debug () { printf \"%-21s\\t%-21s\\t%-21s : %s\\n\" \${FUNCNAME[3]} \${FUNCNAME[2]} \${FUNCNAME[1]} \"\$*\" 1>&2; }
+    else
+        echo "unsupported shell: no functions defined"
+    fi
 }
 pause ()
 {
@@ -78,6 +83,39 @@ report_notargcount ()
     [[ $2 -ge $1 ]] && return 1;
     report_usage need at least $1 arg/s: ${*:3}
 }
+report_notfile () 
+{ 
+    : report the argument is not a File;
+    : date: 2018-02-16;
+    : date: 2022-01-08;
+    [[ -f $1 ]] && return 1;
+    report_usage $1 "ISN'T" a file;
+    declare -f $(myname 2) 1>&2
+}
+report_usage () 
+{ 
+    : writes: usage message of report_... caller FAILURE to STDERR;
+    : date: 2018-03-30;
+    : date: 2022-04-29;
+    : date: 2024-11-14;
+    local caller=$(myname 3);
+    : case $caller in;
+    : diff_pair;
+    : callStack;
+    : read -p "HALT, use ctrl-C" < /dev/tty > /dev/tty;
+    :;
+    : esac;
+    echo USAGE $caller: $* 1>&2
+}
+ignore () 
+{ 
+    : ~ cmmd args ...;
+    : returns STATUS, but not STDOUT;
+    : trace_callstack;
+    : debug $*;
+    : date: 2019-11-23;
+    $@ > /dev/null
+}
 #
 # 2025-12-13: copied from .prior-work-files/lib/fun/utillib
 if_missingargs ()
@@ -115,8 +153,43 @@ setenv ()
     export $na;
     : debug RETURN $na
 }
+timestamp ()
+{
+    : date: 2023-08-07;
+    : debug ENTRY $# $@;
+    report_notfile $1 && return 1;
+    touch -t $(date -r $(epochmtime $1) +%Y%m%d%H%M.%S) $2
+} 
+# 2025-12-14: copied from .prior-work-files/lib/fun/utillib
+epochmtime () 
+{ 
+    : mtime of a file in epoch seconds;
+    : date: 2023-07-22;
+    : date: 2025-12-14: rename for clarity;
+    [[ -f $1 ]] || return;
+    set $(stat -r $1);
+    echo ${10}
+}
 #
 # 2025-12-13: copied from ShellFunctions.md
 fbdy () {
 	declare -f ${@:-fbdy}
 }
+#
+# 2025-12-14: copied from .prior-work-files/lib/fun/cleanlib
+myname () 
+{ 
+    : a calling functions NAME, default MYcaller;
+    : 2 is the callers caller, 3 is theirs, etc...;
+    : date: 2023-07-22;
+    : date: 2025-12-14: POSIX version, zsh / bash diffs;
+    if [ -n "$ZSH_VERSION" ]; then
+       local level=${1:-1}
+       echo ${funcstack[$((level + 1))]}
+    elif [ -n "$BASH_VERSION" ]; then
+        echo ${FUNCNAME[${1:-1}]}
+    else
+	echo "unsupported shell - use zsh or bash"
+    fi
+}
+
