pruning functions

diff --git a/.workbench/backuplib b/.workbench/backuplib
--- a/.workbench/backuplib
+++ b/.workbench/backuplib
@@ -25,9 +25,8 @@ backup ()
     : ~ one or more files down the .bak/.bak/... stack;
     : date: 2023-09-20;
     : date: 2024-08-20;
-    local file;
     backup_init;
-    apply backup_one $@
+    apply backup_one "$@"
 }
 backup_copyright () 
 { 
@@ -64,20 +63,89 @@ backup_files ()
     : date: 2023-10-21;
     indir .bak namedfiles
 }
-backup_init () 
+backup_here () 
 { 
+    : recursively move backups down the stack;
+    : clearing the way for their replacement at the top;
+    : uses: cmp
+    : debug ENTRY $@;
+    set $1 ${BACKUP_DIRECTORY} "${2:-$PWD}";
+    : debug SET $@ $(dirs);
+    [[ -d $2 ]] || mkdir $2;
+    [[ "$3" == "$PWD" ]] && { 
+        : debug TEST: "$3" equal $PWD;
+        cmp $1 $2/$1 2> /dev/null 1>&2 && { 
+            : debug CMP RETURN $(dirs);
+            return
+        }
+    };
+    local mode=$(classic_mode $1);
+    [[ -f $2/$1 ]] && { 
+        : debug DOWN $@ $(dirs);
+        cd $2;
+        backup_here $1 "$3"
+    } || { 
+        mv $1 $2/$1;
+        [[ $3 == $PWD ]] && { 
+            : debug DONE: $@ $(dirs);
+	    echo "dollar3: $3   dollar2: $2  dollar1: #1"
+            cp $2/$1 $1;
+            timestamp $2/$1 $1;
+            chmod $mode $1;
+            cd ..;
+            : debug STACK RETURN $(dirs);
+            return
+        };
+        cd ..;
+        backup_here $1 "$3"
+    }
+}
+backup_init () 
+{
+    # 2026-01-01: TOO: cleanup usage comment
     : establish {BACKUP,VERSION}_DIRECTORY;
     : date: 2023-09-18;
     : date: 2023-09-20;
     : date: 2024-04-30;
     [[ $# -eq 1 ]] && { 
         comment ERROR, Zero or Two args;
-        declare -f $(myname) 1>&2;
         return
     };
     set $@ .bak .ver;
     setenv BACKUP_DIRECTORY $1 > /dev/null;
     setenv VERSION_DIRECTORY $2 > /dev/null
+}
+backup_one () 
+{
+    # 2026-01-01: TODO: revisit the non-local directory operation
+    : for a single file in possible non-local directory;
+    : date: 2023-09-11;
+    : debug ENTRY $PWD $@;
+    : date: 2024-04-29;
+    local file=${1:-/dev/null};
+    report_notfile $file && return 1
+    local file=$(basename $file);
+    local dir=$(dirname $1);
+    ignore pushd $dir;
+    : debug PUSHD $(dirs);
+    : pause;
+    backup_here $file;
+    ignore popd;
+    : debug POPD $(dirs);
+    : pause
+}
+backup_onlyfiles () 
+{ 
+    : candidate backup files, including DOT files;
+    : date: 2026-01-01: use array to handle shell expansion
+    local files=( * .* )
+    apply name_existing "${files[@]}"
+}
+backup_outdated () 
+{ 
+    : backup files no longer used;
+    : uses: comm
+    comm -13 <(backup_onlyfiles) <(indir ${BACKUP_DIRECTORY:-.bak} backup_onlyfiles)
 }
 classic_mode () 
 { 
@@ -94,123 +162,13 @@ file_mode ()
     set -- $(stat -r $1);
     echo $3
 }
-backup_here () 
-{ 
-    : recursively move backups down the stack;
-    : clearing the way for their replacement at the top;
-    : date: 2023-09-11;
-    : date: 2024-04-29;
-    : date: 2023-09-05;
-    debug ENTRY $@;
-    set $1 ${BACKUP_DIRECTORY} "${2:-$PWD}";
-    debug SET $@ $(dirs);
-    : pause;
-    [[ -d $2 ]] || mkdir $2;
-    [[ "$3" == "$PWD" ]] && { 
-        debug TEST: "$3" equal $PWD;
-        cmp $1 $2/$1 2> /dev/null 1>&2 && { 
-            debug CMP RETURN $(dirs);
-            : pause;
-            return
-        }
-    };
-    local mode=$(classic_mode $1);
-    [[ -f $2/$1 ]] && { 
-        debug DOWN $@ $(dirs);
-        : pause;
-        cd $2;
-        backup_here $1 "$3"
-    } || { 
-        mv $1 $2/$1;
-        [[ $3 == $PWD ]] && { 
-            debug DONE: $@ $(dirs);
-            : pause;
-            cp $2/$1 $1;
-            timestamp $2/$1 $1;
-            chmod $mode $1;
-            cd ..;
-            debug STACK RETURN $(dirs);
-            : pause;
-            return
-        };
-        cd ..;
-        backup_here $1 "$3"
-    }
-}
-backup_one () 
-{ 
-    : for a single file in possible non-local directory;
-    : date: 2023-09-11;
-    : debug ENTRY $PWD $@;
-    : date: 2024-04-29;
-    local file=${1:-/dev/null};
-    report_notfile $file && { 
-        : debug NOT file: $file;
-        : pause;
-        return 1
-    };
-    local file=$(basename $file);
-    local dir=$(dirname $1);
-    backup_here $file;
-}
-backup_onlyfiles () 
-{ 
-    : candidate backup files, including DOT or system files;
-    : date: 2023-09-11;
-    : date: 2023-10-21;
-    : date: 2025-12-28: eval and quote to prevent early globbing
-    eval "apply name_existing .* *"
-}
-# 2025-12-28: maybe backup_prunefiles is the new version of backup_sync () 
-backup_outdated () 
-{ 
-    : backup files no longer used;
-    comm -13 <(backup_onlyfiles) <(indir ${BACKUP_DIRECTORY:-.bak} backup_onlyfiles)
-}
-backup_sync () { 
-    : BACKUP Outdated backups and REMOVE them;
-    : a backup is Outdated when there is a backup, but no FILE;
-    : date: 2023-08-29;
-    : date: 2023-09-11;
-    : date: 2023-12-18;
-    debug ENTRY $*;
-    set -- ${@:-$(backup_outdated)};
-    debug SET: $# $@;
-    pause;
-    [[ $# -gt 0 ]] || return;
-    ignore pushd .bak;
-    debug PUSHD $(dirs);
-    pause;
-    backup $@;
-    rm -f $@;
-    debug POPD 0 $(dirs);
-    pause;
-    ignore popd;
-    debug POPD 1 $(dirs);
-    pause;
-    remvds > /dev/null;
-    debug RETURN $(dirs);
-    pause
-}
-file_mode () 
-{ 
-    : permission bits of the file argument;
-    : date: 2023-07-22;
-    report_notfile ${1:-/dev/null} && return 1;
-    set -- $(stat -r $1);
-    echo $3
-}
-# 2025-12-28: WLA backup functions (for a revised backuplib)
-# 2025-12-14: prune .bak/.bak/* files not linked to a .ver/
 backup_prunefiles () {
     : prune bak files not linked to a version
-    : uses: basename, rm, sort, xargs
+    : uses: basename, find, rm, sort, xargs
     for f in $(find .ver -type f); do
 	: debug echo $f
 	find .bak/.bak -name $(basename $f) -links 1
     done | sort -u | xargs rm -v
-}
-backup_needed () {
-    : files in cwd not in .bak/ tree
-    cmp -s $1 .bak/$1 || echo $1;
+    : prune all but the most recent 3 unversioned files
+    find .bak/.bak/.bak -type f -links 1 | xargs printf "pruning(i.e., rm -v): %s\n"
 }
