1st working versionlib

diff --git a/.workbench/versionlib b/.workbench/versionlib
--- a/.workbench/versionlib
+++ b/.workbench/versionlib
@@ -110,4 +110,55 @@ version_files () {
 	print "version: $1 is linked to: $2"
     done
 }
-
+version_new () {
+    : create a new first or next version of a file;
+    : uses: find, sort, tail;
+    : libs: fnusedlib
+    debug ENTRY $# $@;
+    if [ $# -lt 1 ]; then
+	echo "Usage: version_new filename [M|m|p|semvar]" && return 1;
+    elif [[ ! -f .bak/"$1" ]]; then
+	echo "error: .bak/$1 is not a file" && return 1;
+    fi
+    local file=$1
+    if [[ -z $2 ]]; then
+	local bump=patch
+    elif [[ -n "$2" ]]; then
+        case "$2" in
+	    (M) local bump=major ;;
+	    (m) local bump=minor ;;
+	    (p) local bump=patch ;;
+	    (*) if [[ $2 =~ ^[0-9]+(\.[0-9]+)*$ ]]
+                then
+	            local newversion=$2
+		else
+		    printf "ERROR: invalid argument: %s\n" "$2" >&2
+		    return 1
+		fi ;;
+	esac
+    fi
+    echo "bump: $bump OR version: $newversion for $file";
+    if [[ -n $bump ]]; then
+	echo "bump $bump version for $file";
+	: echo "determine previous version or assign 0.0.1"
+	local highest=$(find .ver/ -name $file 2>/dev/null | sort -t'/' -k2 -V | tail -n 1)
+	debug highest: $highest;
+	local currentversion=${${highest#.ver/}%%/*}
+	if [[ -n $currentversion ]]; then
+	    echo "bump $currentversion $bump value"
+	    local newversion=$(version_bump $bump $currentversion)
+	else
+	    case $bump in
+		(major) local newversion=1.0.0 ;;
+		(minor) local newversion=0.1.0 ;;
+		(patch) local newversion=0.0.1 ;;
+		(*) local newversion=0.0.1 ;;
+	    esac
+	fi
+    fi
+    echo "create version $newversion link file for .bak/$file"
+    local verdir=$VERSION_DIRECTORY/$newversion
+    : debug verdir: $verdir
+    [[ ! -d "$verdir" ]] && mkdir -pv $verdir
+    ln -f .bak/$file $verdir/$file
+}
